// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type NewMovie struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CategoryID  string  `json:"categoryId"`
}
